apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: odsext
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - name: odsext
          image: hajedkh/odsext:full-pipe-run-r-s8vtx
          env:
            - name: SOLIFEDB_URL
              value: jdbc:postgresql://postgres:5432/solife
            - name: SOLIFEDB_USER
              value: admin
            - name: SOLIFEDB_PWD
              value: admin
            - name: SOLIFE_DB_DRIER_CLASS
              value: org.postgresql.Driver
            - name: ODSDB_URL
              value: jdbc:postgresql://postgres:5432/solife
            - name: ODSDB_USER
              value: admin
            - name: ODSDB_PWD
              value: admin
            - name: BATCHDB_URL
              value: jdbc:postgresql://postgres:5432/solife
            - name: BATCHDB_USER
              value: admin
            - name: BATCHDB_PASSWORD
              value: admin
            - name: ACTIVEMQ_URL
              value: tcp://activemq-internal:61616
            - name: ACTIVE_PROFILE
              value: manager
            - name: DB_AUTO_DDL
              value: update
          ports:
            - containerPort: 8080
